spring:
  datasource:
    url: jdbc:h2:mem:inventorydb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true

server:
  port: 8080

# OpenAPI UI at /swagger-ui.html
